#!/bin/sh

mkdir -p /tmp/initrd/proc \
    && mkdir -p /tmp/initrd/sys \
    && mkdir -p /tmp/initrd/dev \
    && mkdir -p /tmp/initrd/tmp \
    && mkdir -p /tmp/initrd/newroot \
    && cp /sdk/initrd/init /tmp/initrd \
    && echo $KS_ROOT_HASH > /tmp/initrd/roothash \
    && cd /tmp/initrd \
    && find . | cpio -H newc -o > /output/initrd.cpio
